repos:
# -   repo: https://github.com/hhatto/autopep8
#     rev: 'v2.1.0'
#     hooks:
#     -   id: autopep8

-   repo: https://github.com/pycqa/flake8
    rev: '7.1.0'
    hooks:
    -   id: flake8

# based on https://jaredkhan.com/blog/mypy-pre-commit
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        # this calles the system-wide mypy which may be on a different version than the virtualenv's mypy
        # entry: "mypy --python-executable ./.venv/Scripts/python ./src"
        # this calles mypy from the virtual environment
        entry: "powershell -c \" ./.venv/Scripts/mypy.exe --config-file pyproject.toml $(git ls-files -- src/**/*.py)\""
        language: python
        language_version: python3.10
        # the current settings work for mypy version 0.990 pre-release
        #additional_dependencies: ["mypy>=0.989"]
        # pre-release versions must be cached on a specific place on the disk (not yet tried)
        # additional_dependencies: ["-- find-links=./wheel_cache mypy>=0.989"] 
        # This works and is reasonably fast:
        additional_dependencies: ["git+https://github.com/python/mypy.git"] 
        # check the whole project, not just the files that were changed
        pass_filenames: false
        # trigger for commits changing Python files
        types: [python]
        # use require_serial so that script
        # is only called once per commit
        require_serial: true
        # print the number of files as a sanity-check
        verbose: true

# example config
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v2.3.0
#     hooks:
#     -   id: check-yaml
#     -   id: end-of-file-fixer
#     -   id: trailing-whitespace