[metadata]
name = Frontdown
description = hardlink backup tool
license = GNUv3
license_files = LICENSE.txt
platforms = linux, osx, win32
classifiers = 
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    

[options]
packages = Frontdown,Frontdown.PortableDevices
include_package_data = True
install_requires =
    pydantic==2.13.4,
    comtypes >= 1.4.16; sys_platform=="win32"
python_requires = >=3.10
package_dir =
    =src
zip_safe = False

[options.extras_require]
testing =
    black>=26.5.1
    mypy>=2.3.0
    pyftpdlib>=2.2.0
    pylint>=4.0.6
    pytest>=9.1.1
    pytest-cov>=7.1.0

[options.package_data]
Frontdown = py.typed,template.html
